image: node:20.9.0
pipelines:
  branches:
    dev:
      - step:
          name: Deploy to Dev
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: 'developer'
                SERVER: '128.140.43.32'
                COMMAND: 'cd /var/www/vnu-react && git checkout dev && git pull origin dev && node -v && npm install && npm run build && echo -e "Done" '
